version: "3.8"
services:
  backend_img:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend_img:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true